# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_libA.ipynb.

# %% auto 0
__all__ = ['func_a', 'func_b']

# %% ../nbs/00_libA.ipynb 6
def func_a(a='A', # A variable
           b='B'  # Another variable
          ) -> str: # Just returns a string that identifies the function.
    '''
    A very simple function that returns a string identifying itself.
    '''
    return f"This returned from func_a( {a=}, {b=})"

# %% ../nbs/00_libA.ipynb 16
def func_b(
        c='C',     # A variable named `c`
        d='D'      # Another variable, this one named `d`
        ) -> str:  # It returns a string  
    '''
    Simple function that returns a string to identify itself.
    '''
    return f"This returned from func_b({c=}, {d=})"
